### ISSUE TITLE
Improve/fix unit tests

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1012]
## Issue Overview

There are some unit test-related housekeeping items carried over from codebase:

- [ ] Optimize EE unit tests (mirror some improvements WP made to their unit tests) [8979](https://events.codebasehq.com/projects/event-espresso/tickets/8979)
- [ ] Improve Unit Tests using Event Scenario H [8983](https://events.codebasehq.com/projects/event-espresso/tickets/8983)
- [ ] Improve/fix sporadic failing `EE_Event_Test::test_perform_sold_out_status_check` test [11394](https://events.codebasehq.com/projects/event-espresso/tickets/11394)
- [ ] Fix Waitlist acceptance tests logout action [11408](https://events.codebasehq.com/projects/event-espresso/tickets/11408)
- [ ] Utilize the EeAddonTestCase class for add- system related testcases and convert existing tests over to use that [10682](https://events.codebasehq.com/projects/event-espresso/tickets/10682)
