### ISSUE TITLE
Sprint 5 [Jan 14 - 27] TO DO LIST

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2224]
# New Logic

- [x] #1846 Complete GraphQL Event Type Mutation

- [ ] #2212 Create `i18n` own wrapper for `__` function

___

# Research

- [ ] #2148 Research and Evaluate Strategies for Monitoring Network Connections and Managing Offline Data Storage for Future Persistence

- [ ] #2160 Research and Evaluate Strategies for Implementing Undo Functionality in EDTR

___

# Code Cleanup && Refactoring

- [x] #2227 Move `useMutators` hook into `eventEditor` domain

- [x] #2228 Create Model Entity Specific Context Hooks

- [x] #2229 One Modal To Rule Them ALL: use single modals for datetime edit form, ticket edit form, and ticket price calculator instead of one for each entity

- [x] #2230 Rename Components and Folders
	- [x] rename `\application\ui\components\layout\editor-modal` to `editorModal`

	- [x] rename `\domain\eventEditor\datetimes\DatetimeId.js` to `DatetimeIdTag`(?)

	- [x] rename `\domain\eventEditor\tickets\TicketId.js` to `TicketIdTag`(?)

	- [x] delete `\domain\eventEditor\datetimes\datesList`

	- [x] rename `\domain\eventEditor\datetimes\DatesList` to `datesList`

	- [x] delete `\domain\eventEditor\tickets\ticketsList`

	- [x] rename `\domain\eventEditor\tickets\TicketsList` to `ticketsList`

	- [x] delete `\application\utilities\money\amountsMatch.js`

- [x] #2231 Create New Subfolders and Relocate Files
	- [x] move  `\application\ui\components\forms\editor-modal\FormModal.js`, `FormModalForm.js`, and `styles.css` into new `FormModal` subfolder

	- [x] move  `\application\ui\components\input\CurrencyInput.js` and `InlineEditInput.js` into new subfolders with the same names repespectively

	- [x] move inputs and buttons in `\domain\eventEditor\tickets\ticketPriceCalculator` into subfolder named `inputs`(?)

	- [x] create `\domain\shared\ui` folder

	- [x] move `\domain\shared\RelationsSelector.js` into new `ui` folder

	- [x] #2261 Migrate `useRect()` hook from EDTR v1 to Prototype

- [x] #2232 Reorganize Entity Predicate Logic: create folders for entities inside `\domain\shared\entities`, then add a `predicates` subfolder to each one of those and move predicate functions into them.

- [x] #2233 Remove Entity Type Optional Property Operators:  Remove the optional operator from entity properties in `/domain/eventEditor/data/types.ts`

___

# TypeScript Conversion

- [x] #2129 Domain Context Provider

- [x] #2133 Application Converter Utilities

- [ ] #2132 Application Date Utilities

- [x] #2134 Typefy Toaster and its consumers

- [x] #2135 Typefy ToastProvider and its consumers

- [x] #2235 Convert ContextProviders to TypeScript

- [x] #2236 Convert Event Editor Datetimes Components to TypeScript

- [x] #2237 Convert Event Editor Tickets Components to TypeScript

- [x] #2238 Convert Shared Domain Components to TS

___

# Unit Tests

- [x] #2119 Add Tests for Price Predicates

- [x] #2129 Domain Context Provider

- [x] #2133 Application Converter Utilities

- [ ] #2132 Application Date Utilities

- [x] #2142 Write Tests for Application Hooks

- [ ] #2146 Write Tests for useEditorModalState

- [ ] #2136 Write Tests for Application ToastProvider

- [ ] #2151 Write tests for Ticket Price Calculator

- [x] #2239 Complete Unit Tests for Datetime Mutations

- [x] #2240 Complete Unit Tests for Price Mutations

- [x] #2241 Complete Unit Tests for Ticket Mutations

- [x] #2242 Write Tests for Remaining Application Utilities

- [x] #2243 Add Unit Tests for Datetime Predicates

- [ ] #2244 Add Unit Tests for Ticket Predicates
