### ISSUE TITLE
Sprint 6 [Jan 28 - Feb 10] TO DO LIST

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2296]
# New Logic

- [ ] #2212 Create `i18n` own wrapper for `__` function

___

# Research

- [ ] #2148 Research and Evaluate Strategies for Monitoring Network Connections and Managing Offline Data Storage for Future Persistence

- [ ] #2160 Research and Evaluate Strategies for Implementing Undo Functionality in EDTR

___

# Code Cleanup && Refactoring

___

# TypeScript Conversion

- [ ] #2132 Application Date Utilities

___

# Unit Tests

- [ ] #2132 Application Date Utilities

- [ ] #2146 Write Tests for useEditorModalState

- [ ] #2136 Write Tests for Application ToastProvider

- [ ] #2151 Write tests for Ticket Price Calculator

- [ ] #2244 Add Unit Tests for Ticket Predicates
