### ISSUE TITLE
EDTR Data Handling Checklist

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2797]
on latest `EDTR/master` branch:

- confirm that all CRUD functionality works as expected:

     - [x] entity creation

     - [x] entity editing

     - [x] entity deletion

     - [x] dates and times update correctly with no offset shenanigans

- confirm that all TAM relation logic works as expected

     - [x] existing relations

     - [x] adding new relations

     - [x] removing new relations

     - [x] removing existing relations

     - [x] error states for missing relations

- confirm that all Price Calculator logic works as expected

     - [x] existing prices and price modifiers

     - [x] adding new price modifiers

     - [x] removing new price modifiers

     - [x] removing existing price modifiers

     - [x] reverse calculation -> ticket toal and/or base price

     - [x] base price is always first in list

     - [x] default base price is added if none exists

     - [x] only one base price can be added and does not appear in price type options list for other modifiers

     - [x] new calculated ticket total price is reflected in ticket card or ticket edit form when calculator is closed

     - [x] editing ticket total price from ticket card or ticket edit form is reflected when calculator is opened

- review existing unit test code coverage for data management

     - [x] add unit tests where possible to increase coverage as much as possible (ie: 90% +)

**Comment by manzoorwanijk** [comment]
- For a new and existing event
    - [ ] New Date/Ticket
    - [ ] Inline Edit of fields
    - [ ] Editing fields in modal
    - [ ] ❌ **Date and time has unexpected change, #2753**
    - [ ] Inline date capacity change updates related ticket quantity
    - [ ] ❌ **Date capacity change in modal does NOT update related ticket quantity**
    - [ ] Trashing date/ticket
    - [ ] Trashing date, trashes lone related tickets
    - [ ] Permanent deletion of date deletes lone related tickets
    - [ ] Sorting of dates/tickets

**Comment by manzoorwanijk** [comment]
- TAM (For new and exiting event)
    - [ ] New relations added
    - [ ] Existing relations retained
    - [ ] Existing relations deleted
    - [ ] Newly added relations deleted
    - [ ] Error for orphan dates and tickets

**Comment by manzoorwanijk** [comment]
Some miscellaneous issues
- When publishing a new event
`[12-May-2020 08:57:24 UTC] PHP Notice:  Undefined index: edit_event_datetimes in wp-content/plugins/event-espresso-core/admin_pages/events/Events_Admin_Page.core.php on line 1182`

- Default tickets are repeated multiple times for a new event
![image](https://user-images.githubusercontent.com/18226415/81663512-6031cd00-945c-11ea-948f-40b03990ac9a.png)

- Table view columns have some alignment issue
![image](https://user-images.githubusercontent.com/18226415/81664903-a0de1600-945d-11ea-9ee7-7a5b28f5106a.png)

- When TAM buttons are disabled, tooltip doesn't go away
![image](https://user-images.githubusercontent.com/18226415/81665565-7a6caa80-945e-11ea-86ee-abf583d64d58.png)

**Comment by manzoorwanijk** [comment]
TPC decimal places are messed up when switching reverse calculate
![image](https://user-images.githubusercontent.com/18226415/81666741-0f23d800-9460-11ea-80f0-efb685503702.png)

**Comment by manzoorwanijk** [comment]
### TPC

✅ existing prices and price modifiers

✅ adding new price modifiers

✅ removing new price modifiers

✅ removing existing price modifiers

✅ reverse calculation -> ticket total and/or base price

✅ base price is always first in list

✅ default base price is added if none exists

✅ only one base price can be added and does not appear in price type options list for other modifiers

✅ new calculated ticket total price is reflected in ticket card or ticket edit form when calculator is closed

❌ **editing ticket total price from ticket card or ticket edit form is reflected when calculator is opened**

❌ **editing ticket total price in card or table should recalculate base price**

**Comment by manzoorwanijk** [comment]
If `reverseCalculate` is true, `isTaxable` does not change when adding prices:
Steps:
1. Set `reverseCalculate` to `true` and delete all price modifiers
2. Save and close the modal
3. Reopen the TPC modal and check the value of `isTaxable` in Debug Info
4. Add a tax price

`isTaxable` should change to true but it doesn't

**Comment by manzoorwanijk** [comment]
For prices,
Sent to server `amount: 80.357143`
Received from server `amount: 80.36`
