### ISSUE TITLE
Reports improvements

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#425]
## Issue Overview

This epic covers all work that improves the registration and transaction reports within the EE4 admin.  Currently this list of improvements includes:

* [ ] Allow selection of reporting dates within registration reports
* [ ] Allow selection of reporting dates within transaction reports
* [ ] Allow selection of status within registration reports
* [ ] Allow selection of status within transaction reports

## Related Information:

See [here](https://events.codebasehq.com/projects/event-espresso/tickets/4820) for original ticket

**Comment by nerrad** [comment]
Copied from the original ticket:

Some potential charting libraries to consider:

- https://github.com/uber/react-vis
- https://github.com/reactjs/react-chartjs
- https://github.com/react-d3
- https://github.com/recharts/recharts (see api docs here: http://recharts.org/#/en-US/api/AreaChart)

Out of that list, the one that is most appealing is recharts - their documentation looks straight up awesome and the implementation looks fairly concise and straightforward (including responsive charts which is important for mobile)

**Comment by joshfeck** [comment]
Including one more improvement here:

- [ ] Build additional Registrations and Transactions reports that group per Event ID [9120](https://events.codebasehq.com/projects/event-espresso/tickets/9120)

- [ ]
