### ISSUE TITLE
Refactor Questions, Question Groups, and the Registration Form

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#856]
For backstory: http://p2.eventespresso.com/2016/02/18/changing-questions-question-groups-and-the-registration-form/

- [ ] [Add error handling for when the same question is used in two question groups on the same reg form](https://events.codebasehq.com/projects/event-espresso/tickets/7518)

- [ ] [Add new column to esp_answer table for tracking Question Group ID](https://events.codebasehq.com/projects/event-espresso/tickets/7527)

- [ ] [Refactor and abstract System Questions table and data generation so that additional System Question Groups can be added](https://events.codebasehq.com/projects/event-espresso/tickets/9405)

- [ ] [Add the ability to request only First Name and Last Name (from the Personal Info question group) for additional registrants](https://events.codebasehq.com/projects/event-espresso/tickets/8605)

**Comment by joshfeck** [comment]
Some useful notes from cb8757:

There's still a fair bit that needs to be done on 9413. The bulk of the Registration Form admin page changes are done, specifically the really hard part (the actual dynamic form building), but the following is still needed:

 * DMS for converting existing question group <=> question relations to new format

 * Registration Form admin page input validation section needs to be fixed/updated/completed as it currently only lists the available validation strategies for each input type, but requires some intelligent formatting, as well as some additional fields for controlling variants

 * Input Options settings for multi value input types need to be wired up for existing questions

 * default Input Options settings for other multi value input types need some improvement, ex: the Year input displays 100 options (1916 - 2016)

 * SPCO needs to be refactored to use the additional fields that have been added to EE_Question such as html_id, html_class, etc, which I think will actually be fairly easy and will also hopefully result in SPCO performing less logic to build the forms.

 * the Event Editor Questions section will very likely require some changes... but possibly not. That said, the new setup offers a lot more possibilities, for being able to add question groups for more than just the primary registrant or other registrants, ex: we could add a dropdown for selecting a myriad of options for adding relations to question groups, such as: specific event tickets, specific event datetimes, registrant #2, registrant #3, the last registrant, etc. This kind of logic would be easier to implement after having a Rules system in place that implements the specification pattern. These kinds of changes of course could be added later, and for the time being, we can just make sure that at least the basics work.

 * the Registration Details admin page may also require some changes for displaying answers to registrant questions. This may be easy.

**Comment by joshfeck** [comment]
We're going to need to p2 this and distill all these ideas into a workable plan.
