### ISSUE TITLE
Add support to core for marking payment as refunded when refunds are issued via the gateway

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#859]
This was [originally requested in codebase](https://events.codebasehq.com/projects/event-espresso/tickets/5186) to address an issue with PayPal Standard and IPNs for refunds. While we are not adding new features to PayPal Standard, other gateways may allow for this.

The following tickets were created as well:

- [ ] Add new payment status code PRF for refunds; 7479
- [ ] Update the TXN Admin pages to display refund payments; 7480
- [ ] Update TXN Admin details page to process refund payments using new status; 7481
- [ ] Add Payment Refund status to default table data scripts in EEH_Activation and DMS's; 7482
- [ ] Update gateways that will support the new Refund Payment Status; 7483

A few notes from the above tickets:

@tn3rb:

> in 5186 - EE4 paypal standard: mark payment as refunded in EE when refunded in paypal, when an admin issues a refund via PayPal, an IPN is sent to the WP site, and EE is now going to receive that IPN and uses it's data to record a payment using the new Refund status (PRF). To make things consistent, when an admin issues a refund via the EE TXN details page, we need to also create a payment using the new Refund status (PRF).
> 
> Currently what happens in the EE admin when you issue a refund, is that a payment object with a negative value is created and given a status of Approved (PAP). After this work is completed, ALL refunds, whether issued via a Payment Method Gateway like PayPal, or via the EE admin, will result in a payment using the new Refund status (PRF) and having a positive amount.

@nerrad:

> Are refund payments going to be recorded in the esp_payments table?  If so, then the existing table on transactions details page should automatically pick them up right?  Or is this ticket just to ensure that they ARE picked up?

@tn3rb:

> Yes, refund payments are currently recorded in the esp_payments table but with a negative value and a status of **Approved** (PAP).
> After the work in 7481 is completed, refunds will still be recorded in the esp_payments table but with the new **Refund** status (PRF) and having a positive amount.
> 
> So yes, the Payment Details table on the TXN details admin page will automatically pick up those payments but will most likely require a few simple tweaks to ensure that totals are calculated properly (ie payments with the PRF status are subtracted) and that the status is also reflected in the table row style (status stripe).
