### ISSUE TITLE
Deprecate and/or Remove Unused Classes,Functions, and Files from Core

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#860]
These were originally reported in Codebase:

- [ ] [Annihilate `EEM_Currency_Payment_Method` from EE](https://events.codebasehq.com/projects/event-espresso/tickets/10786)
- [ ] [Deprecate 'FHEE__EE_Session__construct___lifespan' filter when we reach version 4.10 or .11](https://events.codebasehq.com/projects/event-espresso/tickets/11443)
- [ ] [Deprecate currency model and table](https://events.codebasehq.com/projects/event-espresso/tickets/11173)
- [ ] [Remove EE3 options from EE_Config](https://events.codebasehq.com/projects/event-espresso/tickets/11186)
- [ ] [Remove duplicate Thank You page templates](https://events.codebasehq.com/projects/event-espresso/tickets/10831)
- [ ] [deprecate check for "content/uploads/espresso/templates/" in EEH_Template::locate_template()](https://events.codebasehq.com/projects/event-espresso/tickets/9706)
- [ ] [deprecate esp_event_meta.EVT_visible_on](https://events.codebasehq.com/projects/event-espresso/tickets/9479)
- [ ] [Deprecate EEH_Class_Tools](https://events.codebasehq.com/projects/event-espresso/tickets/8339)
- [ ] [Break up EE_Deprecated.php into versioned folders and extract all classes into separate files](https://events.codebasehq.com/projects/event-espresso/tickets/10804)
- [ ] [Remove old custom Invoice/Receipt system](https://events.codebasehq.com/projects/event-espresso/tickets/11451)
- [ ] [Remove `EE_Template_Config::custom_style_sheet` property and all implementations](https://events.codebasehq.com/projects/event-espresso/tickets/11453)
- [ ] [Eliminate usage of `extend_page_route()` and `extend_page_config()` methods in the admin pages](https://events.codebasehq.com/projects/event-espresso/tickets/7357)
- [ ] [Deprecate timezone string in EE_Datetime_Field constructor](https://events.codebasehq.com/projects/event-espresso/tickets/10887)
- - [ ] [Add a corresponding timezone field for each model that utilizes a datetime field](https://events.codebasehq.com/projects/event-espresso/tickets/9115)
- [ ] [Add a deprecated tag on `EEI_Has_Address`](https://events.codebasehq.com/projects/event-espresso/tickets/8850)

**Comment by tn3rb** [comment]
needs :octocat: issues created from all of the original codebase tickets
