### ISSUE TITLE
Update PHPdocBlocks & /docs folder content where needed

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#866]
These are specific areas where the PHPdocBlocks in EE4 core are missing or need to be updated:

- [ ] `Class EEH_Event_Query` [per codebase ticket](https://events.codebasehq.com/projects/event-espresso/tickets/8985)
- [ ] PHP DocBlock for `EEM_Base::get_all()`, update for new default where conditions strategies, and in /[docs](https://events.codebasehq.com/redirect?https://github.com/eventespresso/event-espresso-core/blob/master/docs/G--Model-System/model-querying.md) [notes in codebase](https://events.codebasehq.com/projects/event-espresso/tickets/10610)

These are specific articles for the docs folder in EE4 core that can be updated or added:

- [ ] Update the code style documentation [notes in codebase](https://events.codebasehq.com/projects/event-espresso/tickets/10562)
- [ ] `EE_System` [per codebase ticket](https://events.codebasehq.com/projects/event-espresso/tickets/6769)
- [ ] Write documentation for the Checkin System [per codebase ticket](https://events.codebasehq.com/projects/event-espresso/tickets/9643)
- [ ] Write documentation for Currency System [per codebase ticket](https://events.codebasehq.com/projects/event-espresso/tickets/5542)
