### ISSUE TITLE
Address related pricing and tax issues

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#878]
There are a number of issues relating to price and tax calculations. They matter enough to fix but they involve some complicated issues that require focus.
This Epic is for the related issues which **might** later be addressed in a separate sprint. We might find that in order to get the sprint done initially some of these items will need to be considered & planned for later. 

- [ ] Fix incorrect tax amount that gets displayed on the Ticket Selector when two taxes are set up [8764](https://events.codebasehq.com/projects/event-espresso/tickets/8764)
- [ ] Price modifier not discounting in parallel when discounts are the same weight [7514](https://events.codebasehq.com/projects/event-espresso/tickets/7514)
- [ ] Line Items: Apply ticket price modifiers in parallel when order is the same [7936](https://events.codebasehq.com/projects/event-espresso/tickets/7936)

- [ ] Address general rounding errors, see codebase [8973](https://events.codebasehq.com/projects/event-espresso/tickets/8973) for backstory
- [ ] Fix rounding issue with a taxable product with a price modifier [10022](https://events.codebasehq.com/projects/event-espresso/tickets/10022)

- [ ] Allow Promotion code discounts to be applied *before* surcharges are applied to the total [9865](https://events.codebasehq.com/projects/event-espresso/tickets/9865)

**Comment by joshfeck** [comment]
See also this P2:

http://p2.eventespresso.com/?p=4592

**Comment by joshfeck** [comment]
Further to the above solution proposed in the P2, there are 4 related tickets:

- [ ] Add Tax Zones and Tax Zone Prices tables and change Tickets and Line Items to use Tax Zone instead of simple taxable booelan [10730](https://events.codebasehq.com/projects/event-espresso/tickets/10730

- [ ] Create new tables for Tax Zone and Tax Zone Price [10731](https://events.codebasehq.com/projects/event-espresso/tickets/10731)

- [ ] Modify TKT_taxable and LIN_is_taxable model fields to be int fields instead of booleans [10732](https://events.codebasehq.com/projects/event-espresso/tickets/10732)

- [ ] Build Admin UI for entering Tax Zone information and associating with Tax Prices [10733](https://events.codebasehq.com/projects/event-espresso/tickets/10733)

**Comment by tn3rb** [comment]
if we are going to break things up into separate issues/PRs like the tickets above,
then we should likely add another one for performing the following tasks:

- extracting the existing line item tax calculation logic into its own class
- adding a new tax calculator class for handling the new tax zones
- adding logic for determining which tax calculator to load and handling the results

**Comment by tn3rb** [comment]
needs :octocat: issues created from all of the original codebase tickets
