### ISSUE TITLE
Increase code coverage by adding new unit tests 

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#882]
- [ ] EE List Tables, see [10190](https://events.codebasehq.com/projects/event-espresso/tickets/10190)

- [ ] `EE_Register_CPT`, see [7043](https://events.codebasehq.com/projects/event-espresso/tickets/7043)

- [ ] Offline Payment Method automated unit tests, see [7026](https://events.codebasehq.com/projects/event-espresso/tickets/7026)

- [ ] methods in espresso_events_Pricing_Hooks class, see [10723](https://events.codebasehq.com/projects/event-espresso/tickets/10723)

**Comment by tn3rb** [comment]
needs :octocat: issues created from all of the original codebase tickets
