### ISSUE TITLE
Add cascading delete features

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#883]
Moving related "Deletion Behavior Refactor" milestone from codebase. Which has some related tickets for reference:

- [ ] Cascading Deletion options for models [9984](https://events.codebasehq.com/projects/event-espresso/tickets/9984)
- [ ] Permanently delete any metadata associated with our CPT objects automatically via EEM_CPT_Base when a permanent delete is initiated [9177](https://events.codebasehq.com/projects/event-espresso/tickets/9177)
- [ ] automatically delete related extra meta when deleting an item [6411](https://events.codebasehq.com/projects/event-espresso/tickets/6411)

- [ ] Add bulk delete transactions with chained delete of related registrations & payments[11496](https://events.codebasehq.com/projects/event-espresso/tickets/11496)

See also related GitHub issue #349

**Comment by joshfeck** [comment]
Two further ideas noted by @nerrad , related to allowing contacts to be permanently deleted:

1. Create an option somewhere in EE for purging the database of records prior to a certain date. That way people would just give the date to purge records for, and we can just delete permanently all related data for that date (that means' some contacts might still remain if there are registrations on that contact that are more up to date).
2. Create the ui/ux for deleting permanently transactions and work out the issues related to that (how are line items affected? How are attached registrations affected) and once that is worked out, then allow permanently deleting contacts but ONLY if all related transactions/registrations are deleted.

**Comment by tn3rb** [comment]
needs :octocat: issues created from all of the original codebase tickets

**Comment by joshfeck** [comment]
https://secure.helpscout.net/conversation/959326568/696772/
