### ISSUE TITLE
Fix issues with DMS

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#978]
## Issue Overview

We're anticipating an uptick in migrations from EE3 to EE4 after REM is released, so now is a good time to fix up the DMS to help make for a smoother transition to EE4. 

- [x] avoid unnecesary ALTER TABLE db queries when checking DB in 4.1, 4.3, 4.4, 4.6 and 4.7 DMSs
Same changes as [9530 - avoid unnecesary ALTER TABLE db queries when checking DB](https://events.codebasehq.com/projects/event-espresso/tickets/9530), but to the older DMSs. --> see https://github.com/eventespresso/event-espresso-core/pull/1094

- [x] Shorten DB index lengths to 191 characters in earlier DMSs too
On the 4.9.0 DMS we set the max length of indexes to 191 characters (eg `ATT_email` is a field that's 255 characters long, but we can only index the first 191 characters). That works fine.
However, when someone migrates from EE3, we first use the 4.1.0 DMS, which DOESN'T have that index limit, so they get a DB error -> I investigated this, and actually the 4.1.0 DMS does have the ATT_email index set to 191 characters... but the 4.7 DMS didn't! And that was actually the only index I could find for a column that's over 191 characters but didn't have that limit. So I crammed that small change into https://github.com/eventespresso/event-espresso-core/pull/1094 too

- [x] EE4.1 DMS truncate columns which are smaller
- On https://secure.helpscout.net/conversation/367825157/368119/?folderId=100574 we noticed that EE3's question required column had no character limit, whereas in EE4 it limits it to 100 characters. This can lead to errors when migrating. --> see https://github.com/eventespresso/event-espresso-core/pull/1100

- The EE3 events_attendees.txn_type has a limit of 45 characters, but is passed into the EE4.1 esp_payments.PAY_gateway field which has a limit of 32 characters. (So if it has more than 32 characters, there is an error migrating that payment). EE3's events_attendees.txn_type was used as both a string foreign key for a specific gateway name, but also for general payment notes. In EE4.1, esp_payments.PAY_gateway is only a foreign key, and esp_payments.PAY_extra_accounting (45 characters) is just for notes. --> see https://github.com/eventespresso/event-espresso-core/pull/1101

- [x]  Migrate EE3's events_attendees.txn_type into EE4's esp_payment.PAY_extra_accounting 
Because 4.6 removes the PAY_gateway column. If the EE3's events_attendees.txn_type was used for payment notes, those notes will be preserved. --> see https://github.com/eventespresso/event-espresso-core/pull/1102

- [x] Don't migrate Invoice Address field from Event Espresso 3
More information in https://events.codebasehq.com/projects/event-espresso/tickets/11490 --> see https://github.com/eventespresso/event-espresso-core/pull/1108

- [x] fix conditional in EE_Data_Migration_Manager PHP5.6+ environments
More information in https://events.codebasehq.com/projects/event-espresso/tickets/10595 --> see https://github.com/eventespresso/event-espresso-core/pull/1108

- [x] Fix Undefined index: invoice_css migrating from 4.4 -> 4.5
https://events.codebasehq.com/projects/event-espresso/tickets/7975 --> see https://github.com/eventespresso/event-espresso-core/pull/1108

- [x] Fix database migration error when venues have a quote in certain fields
https://events.codebasehq.com/projects/event-espresso/tickets/9834 --> this was actually fixed a while ago on https://github.com/eventespresso/event-espresso-core/commit/24bb66d26c74bd53f#diff-a250b8c0e91b4dff721141d427ef0c70R472

**Comment by mnelson4** [comment]
I suspect you're right that the DMSs will be important again with REM around; and with EE3 being removed from wp.org.

> Make DMS code more DRY

Ya I think I like your idea there. My only concern will be keeping the refactor within reason (sometimes they blow up and take infinitely long) and making it backward-compatible.

**Comment by joshfeck** [comment]
"Make DMS code more DRY" is actually [your idea](https://events.codebasehq.com/projects/event-espresso/tickets/8519), sorry, I forgot the link to the codebase ticket.

We could probably drop that one and just focus on fixing the specific bugs for now. I've removed it from this issue.

**Comment by mnelson4** [comment]
Oh if it's my idea then I love it! jk. It's in the realm of doable, just those are some pitfalls (as with any refactor really)

**Comment by joshfeck** [comment]
oh for sure

**Comment by mnelson4** [comment]
Kk, so there are now PRs to address all these issues :confetti_ball:

**Comment by tn3rb** [comment]
the following PRs linked to in the initial comment are all closed now:

- #1094
- #1100
- #1102
- #1108 

and all of the "todos" listed in the initial comment are checked off...

so is this issue completed now?

**Comment by joshfeck** [comment]
Yes.
